# Generated by Django 4.1.7 on 2023-02-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_adress_remove_client_cidade_remove_client_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
